entityqueue.entityqueue.*:
  type: config_entity
  label: 'EntityQueue Config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    min_size:
      type: int
      label: 'Restrict this queue to a minimum of'
    max_size:
      type: int
      label: 'and a maximum of'
    handler:
      type: string
      label: 'Handler'
    target_bundles:
      type: sequence
      sequence:
        - type: string
